_vars:
- &instances 1
- &concurrent 1
- &num_requests 100
- &example hello
- &db redis5
- &kind async
- &count ""

bossrun:
  failfast: yes

Processes:
  redis:
    min-instances: 5
    max-instances: 5
    executable-path: ./redis/redis-2.6.0-rc8/src/redis-server
    arguments:
    - redis
    - config/redis.conf
    - unixsocket
    - ./tmp/redis@(seq0).sock
  zerogw:
    executable-path: /usr/bin/zerogw
    arguments:
    - zerogw
    - --config=config/zerogw.yaml
  python:
    min-instances: $instances
    max-instances: $instances
    executable-path: /usr/bin/python3
    arguments:
    - python3
    - code/${kind}_${db}.py
  ab:
    executable-path: /bin/sh
    arguments:
    - sh
    - -c
    - "sleep 2;
      exec ab -k -c $concurrent -n $num_requests http://localhost:8000/${example}_${db}/${count}"
