_vars:
- &instances 1
- &db mongo
- &kind async

bossrun:
  failfast: yes

Processes:
  mongo:
    executable-path: /usr/bin/mongod
    arguments:
    - mongodb
    - --config=config/mongodb.conf
  zerogw:
    executable-path: /usr/bin/zerogw
    arguments:
    - zerogw
    - --config=config/zerogw.yaml
  python:
    min-instances: $instances
    max-instances: $instances
    executable-path: /usr/bin/python3
    arguments:
    - python3
    - code/${kind}_${db}.py
