_vars:
- &instances 1
- &db mysql
- &kind async

bossrun:
  failfast: yes

Processes:
  mysql:
    executable-path: /usr/bin/mysqld
    arguments:
    - mysqld
    - --defaults-file=config/mysql.cnf
  zerogw:
    executable-path: /usr/bin/zerogw
    arguments:
    - zerogw
    - --config=config/zerogw.yaml
  python:
    min-instances: $instances
    max-instances: $instances
    executable-path: /usr/bin/python3
    arguments:
    - python3
    - code/${kind}_${db}.py
