_vars:
- &instances 1
- &db redis
- &kind async

bossrun:
  failfast: yes

Processes:
  redis:
    executable-path: /usr/bin/redis-server
    arguments:
    - redis
    - config/redis.conf
  zerogw:
    executable-path: /usr/bin/zerogw
    arguments:
    - zerogw
    - --config=config/zerogw.yaml
  python:
    min-instances: $instances
    max-instances: $instances
    executable-path: /usr/bin/python3
    arguments:
    - python3
    - code/${kind}_${db}.py
