#!/bin/bash

mysql_install_db --basedir=/usr --defaults-file=config/mysql.cnf
echo 'create table test.counter (value INT);
      insert into test.counter VALUES(0);
      ' | mysqld --defaults-file=config/mysql.cnf --bootstrap
